### ISSUE TITLE
Newtonsoft.dll error with the new realvirtual package.

### ISSUE THREAD

**Issue by garyhil** [game4automation/game4automation-Community#1]
Hi, 

when importing the newest Version of the Package "realvirtual-Professional-2021.09.unitypackage" in the Unity Editor Version "2021.3.13f1" i get an error saying that there are too many Newtonsoft.dll files.

one in <ProjectDirectory>/PackageCache/<Newtonsoft>/Runtime/...
one in <ProjectDirectory>\Assets\game4automation\private\Interfaces\TwinCATHMI/...

"hard delete" of any of those resolves the error, (obviously) however some functionalities won't work anymore (in my case the CAD Importer".

Cheers Gary

**Comment by game4automation** [comment]
Hi, our Support Forum is here:
https://forum.realvirtual.io

You can delete the Newtonsoft dll. We know the issue and in todays or tomorrows release it will be solved.

See more here on our documentation page:
https://doc.realvirtual.io/advanced-topics/newtonsoft-json
